### ISSUE TITLE
Please read the Advent of Code FAQ regarding rules around the use of AI

### ISSUE THREAD

**Issue by BretHudson** [MrBrownNL/Advent-of-Code-2024#2]
> **Can I use AI to get on the global leaderboard?** Please don't use AI / [LLMs](https://en.wikipedia.org/wiki/Large_language_model) (like GPT) to automatically solve a day's puzzles until that day's global leaderboards are full. By "automatically", I mean using AI to do most or all of the puzzle solving, like handing the puzzle text directly to an LLM. The leaderboards are for human competitors; if you want to compare the speed of your AI solver with others, please do so elsewhere. (If you want to use AI to help you solve puzzles, I can't really stop you, but I feel like it's harder to get better at programming if you ask an AI to do the programming for you.)

https://adventofcode.com/2024/about#:~:text=Can%20I%20use,programming%20for%20you.)

**Comment by MrBrownNL** [comment]
You are absolutely right and it was not the intention to get on the global leaderboard.
A challenge was to automate the initial process as much as possible. Unfortunately, the function to send the answer was also triggered, which was of course not the intention. This has been resolved in any case.
