### ISSUE TITLE
Please wait before leaderboard is full to use LLMs to automate AoC

### ISSUE THREAD

**Issue by Bikatr7** [MrBrownNL/Advent-of-Code-2024#3]
Even if it's for your own learning, some of us are actually trying to get times legitimately. Thank you.

**Comment by MrBrownNL** [comment]
You are absolutely right and it was not the intention to get on the global leaderboard.
A challenge was to automate the initial process as much as possible. Unfortunately, the function to send the answer was also triggered, which was of course not the intention. This has been resolved in any case.

**Comment by BillJWatts** [comment]
Ironically @MrBrownNL, it looks like Bikatr7 was only trying to get another LLM user out the way so he could secure higher scores with his own LLM solver

Unless @Bikatr7 you feel like you can prove me wrong and show yourself solving AOC questions in less than 30 seconds... or even just share your solutions.

**Comment by Bikatr7** [comment]
Hey,

My solutions have already been shared on my Twitter, and my blog (https://kadenbilyeu.com/blog) has plenty of info on my approach, logic, and thought process. It’s all out there, and you’re welcome to review it.

That said, please refrain from making baseless accusations without evidence. If you have questions or concerns, I’m happy to discuss them in good faith. But throwing around wild accusations helps no one.

For context, there are people with documented LLM usage and others with genuinely impossible times who haven’t received this level of scrutiny. If the goal is fairness, I’d suggest focusing there instead of engaging in witch hunts.

Lastly, I’d appreciate it if people avoided dragging in third parties who aren’t directly involved. I’m available to have this conversation individually or publicly, as I already have.

Thanks,
Bikatr7

**Comment by Bikatr7** [comment]
Oh and sorry for pinging you but in case you don't see @BillJWatts

Have a great night.

**Comment by BillJWatts** [comment]
Sincere and honest apologies if you are solving things legitimately, and thank you for sharing some insight on your process.

But you can understand the scrutiny, you're currently  topping the AOC leaderboard and outperforming LLMs, which if true, is extremely impressive. 

Reading your blog, your explanation is akin to "I read, solve and write things very fast", which again, if you are performing at that level (considerably faster than anyone in any previous years) then colour me very very impressed. But I'd hardly say that exaplanation really does much to douse the flames of doubt if you will. 

Not that you need to prove anything to anyone, you're free to do as you please, but don't be surprised that people will cast doubt given your current performance. It's also a competitive environment, scrutiny comes with the territory.  

Regarding dragging third parties in, this is your issue.

**Comment by Bikatr7** [comment]
Zero offense taken. You and other people's skepticism is warranted which is why I've done my best to help dissuade these claims.

Regarding doing better than other people, I'll say that i’m a bit overtuned for these easy problems. (I spent a decent amount of time in November just procuring previous problems lol)

You can expect my times to get higher as more difficult problems come out (whether one wants to attribute this to use of LLMs is up to the individual, I still hope to out perform them as I do believe LLMs can't solve the big problems.) Also I must note that a lot of top players from previous years aren't participating, minus a few exceptions.

But again, minus that one day I have been handely beaten by a few obvious LLM users and my other times (part 2s mostly are much more common).

And I must express, I don't feel that it's that impressive, aside from Day 9, which let's face it, was luck. 

Regarding third parties, what I meant was piggybacking on another issue here, but I guess I did technically provoke that.
